### PR TITLE
Implement module functionality properly

### PR DESCRIPTION
**Pull request by tmysik**
Avoid implementation dependencies and file change listeners. Remove useless
classes. Run test file properly.

One drawback: if no test file for the saved file exists, dialog with a message is shown. This behaviour cannot be easily avoided in NB 8.0 but will be "fixed" in NB 8.1 (see [1]).

[1] https://netbeans.org/bugzilla/show_bug.cgi?id=255350

### CODE REVIEW

**Comment by Caffe1neAdd1ct** [comment]
Hi @tmysik 

Thanks very much, having a read through now :+1: 

I'm thinking of leaving the current implementation for 8.0.0, 8.0.1, 8.0.2 and 8.1 beta, then applying your pull request for 8.1 prod as constant popups are a pain when coding. This would rely on the bug being fixed, having a look at the bug report now also.

My first attempt at making this module had a similar implementation and i remember the dialog box issue from back then, i decided to try and find a way around it, unfortunately the only way i could find (having very limited Java skills) was to use the PhpProject and PhpTesting modules...

**Comment by tmysik** [comment]
@Caffe1neAdd1ct 

Completely up to you to accept or refuse this pull request. :) Your plan sounds fine to me.

**Comment by Caffe1neAdd1ct** [comment]
@tmysik 

Ah the but is already fixed :+1: great stuff, do you know if it will be included in the final release of 8.1 stable?

**Comment by tmysik** [comment]
@Caffe1neAdd1ct 

Yes, it will (the ```Target Milestone``` of that bug is set to 8.1).

**Pull request merged**
